### ISSUE TITLE
Update favicons

### ISSUE THREAD

**Issue by athowes** [epinowcast/primarycensored#139]
**Describe the bug**

The favicons have not been updated.

**To Reproduce**

Look in the `pkgdown` folder.

**Expected behavior**

The favicons to be updated.

**Comment by seabbs** [comment]
So the favicons have been updated using `build_favicons` but it looks like this doesn't catch the apple ones for some reason. I'll destroy the folder and rebuild

**Comment by seabbs** [comment]
Did this. Does it show up as working for you now (see the dev site)
