### ISSUE TITLE
Is "sone" a misspelling?

### ISSUE THREAD

**Issue by athowes** [epinowcast/primarycensored#169]
In e.g.

https://github.com/epinowcast/primarycensored/blob/d65f69c4722508919142ae12df8ca61d1f1deb09/inst/stan/functions/primarycensored.stan#L261

Should this be "some" (as in a generic one)? (Also a mildly odd word choice.)

**Comment by seabbs** [comment]
No it is meant to stand for secondary one but open to other names here

**Comment by athowes** [comment]
(Currently don't have enough context to know what "secondary" in "secondary one" means, so don't have suggestions for other names -- feel free to close.)

**Comment by seabbs** [comment]
Its secondary event censoring - I am not certain what a better name is for these helpers but I think there are better names
