### ISSUE TITLE
Revert to using size over num_elements in stan code

### ISSUE THREAD

**Issue by seabbs** [epinowcast/primarycensored#181]
#177 (fixed in #178) found a type instability when using `size` on M series Macbooks. This seems to have been fixed upstream but the fix isn't with users yet. When it is we should test and revert to using `size()` as the syntax is easier to pass.

**Comment by seabbs** [comment]
As reported by @sbfnk it looks like this isn't yet fixed upstream: https://github.com/epinowcast/primarycensored/pull/178#issuecomment-2535473604

**Comment by sbfnk** [comment]
Turns out the opposite is the case: with the upstream changes #178 no longer fixes #177 (because `num_elements()` now returns a long int).

**Comment by sbfnk** [comment]
Digging a bit deeper the offending line is 

https://github.com/epinowcast/primarycensored/blob/2cfa80242e406533f41eba9c1f33472e2af3ff82/inst/stan/functions/primarycensored.stan#L41

and the issue is 

> Each direct non-static data member named by the designated initializer is initialized from the corresponding brace-or-equals initializer that follows the designator. **Narrowing conversions are prohibited**.

https://en.cppreference.com/w/cpp/language/aggregate_initialization
