### ISSUE TITLE
Broken website links

### ISSUE THREAD

**Issue by jamesmbaazam** [epinowcast/primarycensored#184]
Some links still point to the old package name and are therefore broken. Example:
- https://primarycensoreddist.epinowcast.org/stan/ instead of https://primarycensored.epinowcast.org/stan/

**Comment by jamesmbaazam** [comment]
Ah, yes, I forgot about the dev site but that's broken too: https://primarycensored.epinowcast.org/dev/stan/.

**Comment by seabbs** [comment]
https://primarycensored.epinowcast.org/stan/ this works for me. I haven't worked out a way to build the stan docs on main and dev so they all just go to one link

**Comment by jamesmbaazam** [comment]
For some reason, it now works for me too on the main site, so happy for you to close this issue.

**Comment by seabbs** [comment]
Super weird. Is that the only link you found?

**Comment by seabbs** [comment]
I think this must have been some kind of cache issue or something as searching the package I see 0 instances of the old name (https://github.com/search?q=repo:epinowcast/primarycensored%20primarycensoreddist&type=code).

**Comment by jamesmbaazam** [comment]
> I think this must have been some kind of cache issue or something as searching the package I see 0 instances of the old name ([github.com/search?q=repo:epinowcast/primarycensored%20primarycensoreddist&type=code](https://github.com/search?q=repo:epinowcast/primarycensored%20primarycensoreddist&type=code)).

This might explain it.
